### ISSUE TITLE
The project can't be complied in XE2

### ISSUE THREAD

**Issue by trudger123** [jrathlev/Delphi-Windows-VSS#1]
[DCC Error] WinDevUtils.pas(376): E2003 Undeclared identifier: 'FindVolumeClose'

**Comment by jrathlev** [comment]
_FindVolumeClose_ is defined in _Winapi.Windows_ of **Delph 10**. It is missing in Delphi XE2. 

_WinDevUtils.pas_ was updated to fix this issue.
